### ISSUE TITLE
format JSON responses in gist

### ISSUE THREAD

**Issue by ScotterC** [peterkomar/qrestclient#17]
Maybe use a json formatting library to add white spacing to the response when copying/sharing?

**Comment by peterkomar** [comment]
Could you show me example how it looks like?

**Comment by ScotterC** [comment]
Here's a way to do it in python
http://stackoverflow.com/a/1920585/364120

here's an online one https://jsonformatter.curiousconcept.com/

C++ related question http://stackoverflow.com/questions/17514611/formatting-and-parsing-a-json-string-using-c

C++ json parser - might not be useful

**Comment by peterkomar** [comment]
got it. Yes it will be helpful in viewing request/response. Ok thanks will add

**Comment by peterkomar** [comment]
Added
