### ISSUE TITLE
Problem on windows for 2.1.0

### ISSUE THREAD

**Issue by fithisux** [peterkomar/qrestclient#23]
Hand compiled with mingw64+msys2 has no problems (on windows 10 x64).

The binary included throws a very common error

' The application failed to start because it could not find or load the Qt platform plugin "windows" '

It is a problem with Qt and how it is included in the package.

**Comment by peterkomar** [comment]
Thanks. Was issue in Inno Setup Compiler file. Now it fixed and setup file was updated.
